import {
  Activity,
  Antenna,
  BarChart3,
  Bell,
  Binary,
  BookOpen,
  Bookmark,
  Bot,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Cable,
  Calendar,
  Camera,
  CircuitBoard,
  CircleCheck,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  EthernetPort,
  File,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderKanban,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  Heart,
  Home,
  Image,
  Inbox,
  Key,
  Laptop,
  Layers,
  LayoutDashboard,
  Leaf,
  Lightbulb,
  LineChart,
  List,
  Lock,
  Mail,
  Map,
  MapPin,
  Megaphone,
  Monitor,
  Music,
  Network,
  Package,
  Palette,
  PenTool,
  Phone,
  PieChart,
  Radio,
  Rocket,
  Router,
  SatelliteDish,
  Server,
  Settings,
  Shield,
  ShieldAlert,
  ShoppingCart,
  Smile,
  Sparkles,
  Star,
  Target,
  Terminal,
  TreePine,
  Trophy,
  Truck,
  Users,
  Video,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/** Catalogo curado de icones para aparencia de projeto (board.icon = chave). */
export const ICON_CATALOG: Record<string, LucideIcon> = {
  rocket: Rocket,
  target: Target,
  flag: Flag,
  star: Star,
  heart: Heart,
  zap: Zap,
  flame: Flame,
  trophy: Trophy,
  sparkles: Sparkles,
  lightbulb: Lightbulb,
  briefcase: Briefcase,
  calendar: Calendar,
  clock: Clock,
  bell: Bell,
  bookmark: Bookmark,
  inbox: Inbox,
  folder: Folder,
  "folder-kanban": FolderKanban,
  file: File,
  layers: Layers,
  "layout-dashboard": LayoutDashboard,
  "circle-check": CircleCheck,
  list: List,
  code: Code,
  terminal: Terminal,
  bug: Bug,
  cpu: Cpu,
  database: Database,
  server: Server,
  cloud: Cloud,
  network: Network,
  wifi: Wifi,
  router: Router,
  firewall: ShieldAlert,
  monitor: Monitor,
  laptop: Laptop,
  "hard-drive": HardDrive,
  "circuit-board": CircuitBoard,
  cable: Cable,
  antenna: Antenna,
  "satellite-dish": SatelliteDish,
  radio: Radio,
  "ethernet-port": EthernetPort,
  binary: Binary,
  bot: Bot,
  globe: Globe,
  map: Map,
  "map-pin": MapPin,
  compass: Compass,
  palette: Palette,
  brush: Brush,
  "pen-tool": PenTool,
  camera: Camera,
  image: Image,
  music: Music,
  video: Video,
  megaphone: Megaphone,
  "shopping-cart": ShoppingCart,
  "dollar-sign": DollarSign,
  "credit-card": CreditCard,
  gift: Gift,
  package: Package,
  truck: Truck,
  users: Users,
  smile: Smile,
  coffee: Coffee,
  leaf: Leaf,
  "tree-pine": TreePine,
  "flask-conical": FlaskConical,
  wrench: Wrench,
  hammer: Hammer,
  settings: Settings,
  shield: Shield,
  lock: Lock,
  key: Key,
  "bar-chart": BarChart3,
  "line-chart": LineChart,
  "pie-chart": PieChart,
  activity: Activity,
  mail: Mail,
  phone: Phone,
  home: Home,
  building: Building2,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
};

export const ICON_NAMES = Object.keys(ICON_CATALOG);
export const DEFAULT_BOARD_ICON = "folder-kanban";

export function getBoardIcon(name: string | null | undefined): LucideIcon {
  return (name && ICON_CATALOG[name]) || ICON_CATALOG[DEFAULT_BOARD_ICON];
}
